[tool.poetry]
name = "pytune_helpers"
version = "1.2.0"
description = "Helper package for PyTune platform, including email services and background task handling with Celery and RabbitMQ."
authors = ["Gabriel de Fombelle <gabriel.de.fombelle@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.12"
aiosmtplib = "^1.1.6"
celery = "^5.3.1"
kombu = "^5.3.0"  # Utilisé par Celery pour les communications avec RabbitMQ
simple_logger = { git = "https://github.com/gdefombelle/simple_logger.git" }
pytune_configuration = { git = "https://github.com/gdefombelle/pytune_configuration.git"}

[tool.poetry.dev-dependencies]
pytest-asyncio = "^0.21.1"
mypy = "^1.6.0"
flake8 = "^6.1.0"
black = "^23.9.1"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
